# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./seed_database.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./db-data/:/var/lib/postgresql/data/
  web:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - .env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${EXTERNAL_PORT}:${PORT}"

