# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./seed_database.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./db-data/:/var/lib/postgresql/data/

